name: EcoBundle
version: '${project.version}'
main: org.info_0.ecobundle.EcoBundle
api-version: '1.20'
folia-supported: true
author: 'info_0'
depend: [Vault]
commands: 
    deposit:
        permission: "eco-bundle.deposit"
        usage: "/deposit <gold-amount | all>"
        description: "Deposit golds."
    withdraw:
        permission: "eco-bundle.withdraw"
        usage: "/withdraw <gold-amount | all>"
        description: "Withdraw golds."