name: EcoBundle
version: '${project.version}'
main: org.info_0.ecobundle.EcoBundle
api-version: '1.20'
folia-supported: true
author:
- info_0
- MrSugar
depend: [Vault]
commands: 
    deposit:
        permission: "eco-bundle.deposit"
        usage: "/deposit <gold-amount | all>"
        description: "Deposit golds."
    withdraw:
        permission: "eco-bundle.withdraw"
        usage: "/withdraw <gold-amount | all>"
        description: "Withdraw golds."
    balance:
        permission: "eco-bundle.balance"
        usage: "/balance [player]"
        description: "Balance."
    baltop:
        permission: "eco-bundle.baltop"
        usage: "/baltop"
        description: "Baltop."